### DISCUSSION TITLE
obscure config error

### DISCUSSION THREAD

**Discussion by inductor** [open-telemetry/opentelemetry-ruby#954] [Q&A]
**Description of the bug**

Hi, I'm trying to use this plugin with rails and I get the following error but it looks very vague and not sure what's causing.

```
E, [2021-09-21T13:46:51.454756 #7] ERROR -- : OpenTelemetry error: unexpected configuration error due to uninitialized constant OpenTelemetry::Exporter - OpenTelemetry::SDK::ConfigurationError
```

My config is as follows

```ruby
OpenTelemetry::SDK.configure do |c|
    c.use 'OpenTelemetry::Instrumentation::Rails'
    c.use 'OpenTelemetry::Instrumentation::Mysql2'
    c.use 'OpenTelemetry::Instrumentation::Redis'
    c.add_span_processor(
      OpenTelemetry::SDK::Trace::Export::BatchSpanProcessor.new(
        exporter: OpenTelemetry::Exporter::Jaeger::AgentExporter.new(host: 'simplest-agent.observability', port: 6831)
      )
    )
    c.service_name = 'app'
    c.service_version = '0.1.0'
  end
```

I'm running this on EKS

**Share details about your runtime**

Operating system details: Linux, Ubuntu 20.04 LTS
RUBY_ENGINE: "ruby"
RUBY_VERSION: "2.7.2"
RUBY_DESCRIPTION: "ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]"

**Share a simplified reproduction if possible**

**Comment by arielvalentin** [comment]
@inductor could you share how you are loading your dependencies and requiring the exporter? 

E.g. Are you using a Gemfile + `Bundler.require`?

**Comment by inductor** [comment]
Hi @arielvalentin 
This is our changes https://github.com/cloudnativedaysjp/dreamkast/pull/859/files

I modified requires now, and got this error.

I think name resolve is working and so is my jaeger and now wondering what this error shows.

```
E, [2021-09-21T15:29:41.252817 #7] ERROR -- : OpenTelemetry error: unexpected configuration error due to exporter {:exporter=>#<OpenTelemetry::Exporter::Jaeger::AgentExporter:0x0000558abdd1ca70 @client=#<OpenTelemetry::Exporter::Jaeger::Thrift::Agent::Client:0x0000558abdd1c8e0 @iprot=#<Thrift::CompactProtocol:0x0000558abdd1c980 @trans=#<OpenTelemetry::Exporter::Jaeger::Transport:0x0000558abdd1ca48 @socket=#<UDPSocket:fd 6, AF_INET, 10.100.192.250, 41170>, @buffer=#<Thrift::MemoryBufferTransport:0x0000558abdd1c9f8 @buf="", @index=0>>, @last_field=[0], @boolean_value=nil, @rbuf="\x00\x00\x00\x00\x00\x00\x00\x00">, @oprot=#<Thrift::CompactProtocol:0x0000558abdd1c980 @trans=#<OpenTelemetry::Exporter::Jaeger::Transport:0x0000558abdd1ca48 @socket=#<UDPSocket:fd 6, AF_INET, 10.100.192.250, 41170>, @buffer=#<Thrift::MemoryBufferTransport:0x0000558abdd1c9f8 @buf="", @index=0>>, @last_field=[0], @boolean_value=nil, @rbuf="\x00\x00\x00\x00\x00\x00\x00\x00">, @seqid=0>, @max_packet_size=65000, @shutdown=false, @sizing_transport=#<OpenTelemetry::Exporter::Jaeger::AgentExporter::SizingTransport:0x0000558abdd1c890 @size=0>, @sizing_protocol=#<Thrift::CompactProtocol:0x0000558abdd1c868 @trans=#<OpenTelemetry::Exporter::Jaeger::AgentExporter::SizingTransport:0x0000558abdd1c890 @size=0>, @last_field=[0], @boolean_value=nil, @rbuf="\x00\x00\x00\x00\x00\x00\x00\x00">, @timeout=10.0>} does not appear to be a valid exporter - OpenTelemetry::SDK::ConfigurationError
```

**Comment by inductor** [comment]
netcat shows the port for this host is open

```
root@dreamkast-b8bcd97f8-xm9hc:/app# nc -v -u -z -w 3 simplest-agent.observability 6831
DNS fwd/rev mismatch: simplest-agent.observability.svc.cluster.local != 10-100-216-9.simplest-collector-headless.observability.svc.cluster.local
```

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: service-agent
    app.kubernetes.io/instance: simplest
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: simplest-agent
    app.kubernetes.io/part-of: jaeger
  name: simplest-agent
  namespace: observability
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: zk-compact-trft
    port: 5775
    protocol: UDP
  - name: config-rest
    port: 5778
  - name: jg-compact-trft
    port: 6831
    protocol: UDP
  - name: jg-binary-trft
    port: 6832
    protocol: UDP
  selector:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: simplest
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: simplest
    app.kubernetes.io/part-of: jaeger
```
