### ISSUE TITLE
telemetry missing if project_name is set

### ISSUE THREAD

**Issue by bastelfreak** [open-telemetry/opentelemetry-ruby#794]
Hi people,
I maintain a Rails+sidekiq project where I got a PR that adds opentelemetry support: https://github.com/voxpupuli/vox-pupuli-tasks/pull/272. The following config works fine:

```ruby
# config/application.rb
OpenTelemetry::SDK.configure do |c|
  require 'pg'
  c.use 'OpenTelemetry::Instrumentation::PG'
  c.use 'OpenTelemetry::Instrumentation::Rails'
  c.use 'OpenTelemetry::Instrumentation::Sidekiq'

  c.add_span_processor(
    OpenTelemetry::SDK::Trace::Export::BatchSpanProcessor.new(
      OpenTelemetry::Exporter::Jaeger::AgentExporter.new(host: '127.0.0.1', port: 6831)
    )
  )
end
```

This works fine. jaeger is running from docker with the following docker-compose file:

```yaml
  jaeger:
    image: jaegertracing/all-in-one:1.22
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "5778:5778"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "9411:9411"
      - "14268:14268"
      - "14250:14250"
      - "16686:16686"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
```

In the jaeger UI, my rails app is listed as unknown_service:

![jaeger](https://user-images.githubusercontent.com/341866/120898489-5c568700-c62b-11eb-817e-63a2480eb5da.jpg)

I also verified that data is coming with `tcpdump -i lo port 6831`

---

Now I saw in your README.md that I can set a version/service name:

```ruby
OpenTelemetry::SDK.configure do |c|
  require 'pg'
  c.use 'OpenTelemetry::Instrumentation::PG'
  c.use 'OpenTelemetry::Instrumentation::Rails'
  c.use 'OpenTelemetry::Instrumentation::Sidekiq'

  c.add_span_processor(
    OpenTelemetry::SDK::Trace::Export::BatchSpanProcessor.new(
      OpenTelemetry::Exporter::Jaeger::AgentExporter.new(host: '127.0.0.1', port: 6831)
    )
  )
  c.service_name = 'vox-pupuli-tasks'
  c.service_version = VERSION
end
```

If I set service_name and/or service_version and restart the app + jaeger, the service doesn't appear in the UI. I did the tcpdump again and didn't saw any packets. Please let me know if you've any clue/need more information.
