### ISSUE TITLE
XRay not working

### ISSUE THREAD

**Issue by scar-lovevery** [open-telemetry/opentelemetry-ruby#832]
Not sure if it's related to:
https://github.com/open-telemetry/opentelemetry-collector/issues/3405
or
https://github.com/aws-observability/aws-otel-collector/issues/537
Seems like both of these indicate that the trace id wasnt correctly generated, which i'm also guessing is the issue i'm facing.

I'm getting a similar behavior to the above issues.

When sending data to the aws-otel-collector I'm getting the "Permanent error: SerializationException" much like they are.  I have tried many different configurations.  

I know that the aws-otel-collector is configured correctly if I run a java example, I get traces forwarded to XRay:
```
# create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: aws-otel-eks
  labels:
    name: aws-otel-eks
---
# create deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-otel-eks
  namespace: aws-otel-eks
  labels:
    name: aws-otel-eks
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aws-otel-eks
  template:
    metadata:
      labels:
        name: aws-otel-eks
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: aws-otel-emitter
          image: "aottestbed/aws-otel-collector-java-sample-app:0.9.0"
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://aws-otel-collector.example.svc.cluster.local:4317"
            - name: OTEL_RESOURCE
              value: ClusterName=example
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=AWSObservability,service.name=CloudWatchEKSService"
            - name: S3_REGION
              value: eu-central-1
            - name: LISTEN_ADDRESS
              value: "0.0.0.0:4567"
          imagePullPolicy: Always
        - name: curl
          imagePullPolicy: Always
          image: ellerbrock/alpine-bash-curl-ssl:latest
          command: [ "/bin/bash", "-c", "sleep 10; while :; do curl localhost:4567/outgoing-http-call > /dev/null 1>&1; sleep 2; curl localhost:4567/aws-sdk-call > /dev/null 2>&1; sleep 5; done" ]
```

I'm attempting to use the XRay propagator (0.18.0)
Tried(environment var) OTEL_PROPAGATORS:
          value: xray,tracecontext,baggage
&
          value: tracecontext,baggage,xray
& (this one is very angry)
          value: xray

Is that all that needs to be configured to use that?

The ruby app is configured correctly to export using otlp.  With the collector I'm able to print the trace data if I just use the logging exporter, just doesnt work with XRay.

Wondering if the XRay propagator works?  Or more likely I'm using it incorrectly?  I'd love some help or ideas to try.

Seems like it's not sending 'X-Amzn-Trace-Id' in the logs of the collector, Is there an example somewhere how to configure the ruby sdk with XRay correctly?
